export const SET_IMAGES = "setImages"
export const SET_SEARCH_VALUE = "setSearchValue"
export const SET_AMOUNT = "setAmount"
export const SET_DIALOG = "setDialog"
export const CLOSE_DIALOG = "closeDialog"